import assert from "node:assert/strict";
import test from "node:test";

import {
  findOwnedTotpFactor,
  getMfaSessionState,
  getTotpFactorInventory,
  isPlausibleFactorId,
  isSafeTotpEnrollmentSecret,
  isSafeTotpQrCode,
  isTotpCode,
} from "../../app/_lib/auth/mfa.ts";
import { getSafeAdminRedirect } from "../../app/_lib/auth/redirects.ts";

const verifiedFactor = {
  factor_type: "totp",
  friendly_name: "FoodForFun Atlas authenticator",
  id: "34e770dd-9ff9-416c-87fa-43b31d7ef225",
  status: "verified",
};

const totpQrCodePrefix = "data:image/svg+xml;utf-8,";
const supabaseSvgHeader = `<?xml version="1.0"?>
<!-- Generated by SVGo -->
<svg width="195" height="195"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">`;
const blackQrRect =
  '<rect x="12" y="12" width="3" height="3" style="fill:black;stroke:none"/>\n';
const whiteQrRect =
  '<rect x="15" y="12" width="3" height="3" style="fill:white;stroke:none"/>\n';

function createSupabaseQrSvg(rectPairs: number) {
  return `${supabaseSvgHeader}\n${`${blackQrRect}${whiteQrRect}`.repeat(rectPairs)}</svg>`;
}

function asRawSvgDataUri(svg: string) {
  return `${totpQrCodePrefix}${svg}`;
}

function asPercentEncodedSvgDataUri(svg: string) {
  return `${totpQrCodePrefix}${encodeURIComponent(svg)}`;
}

test("TOTP codes require exactly six ASCII digits", () => {
  assert.equal(isTotpCode("123456"), true);
  assert.equal(isTotpCode("12345"), false);
  assert.equal(isTotpCode("1234567"), false);
  assert.equal(isTotpCode("１２３４５６"), false);
  assert.equal(isTotpCode("123 456"), false);
  assert.equal(isTotpCode("abcdef"), false);
});

test("factor lookup accepts only an owned TOTP factor in the required state", () => {
  const unverifiedFactor = {
    ...verifiedFactor,
    id: "34e770dd-9ff9-416c-87fa-43b31d7ef226",
    status: "unverified",
  };
  const otherFactor = {
    ...verifiedFactor,
    factor_type: "phone",
    id: "34e770dd-9ff9-416c-87fa-43b31d7ef227",
  };
  const factors = [verifiedFactor, unverifiedFactor, otherFactor];

  assert.deepEqual(
    findOwnedTotpFactor(factors, verifiedFactor.id, "verified"),
    verifiedFactor,
  );
  assert.equal(
    findOwnedTotpFactor(factors, verifiedFactor.id, "unverified"),
    null,
  );
  assert.equal(
    findOwnedTotpFactor(factors, unverifiedFactor.id, "unverified"),
    unverifiedFactor,
  );
  assert.equal(
    findOwnedTotpFactor(factors, otherFactor.id, "verified"),
    null,
  );
  assert.equal(
    findOwnedTotpFactor(
      factors,
      "34e770dd-9ff9-416c-87fa-43b31d7ef999",
      "verified",
    ),
    null,
  );
  assert.equal(findOwnedTotpFactor(factors, "not-a-factor", "verified"), null);
});

test("factor IDs must be canonical UUIDs", () => {
  assert.equal(isPlausibleFactorId(verifiedFactor.id), true);
  assert.equal(isPlausibleFactorId("not-a-factor"), false);
  assert.equal(
    isPlausibleFactorId("34e770dd-9ff9-016c-87fa-43b31d7ef225"),
    false,
  );
});

test("TOTP enrollment secrets accept only bounded Base32 values", () => {
  assert.equal(isSafeTotpEnrollmentSecret("JBSWY3DPEHPK3PXP"), true);
  assert.equal(isSafeTotpEnrollmentSecret("too-short"), false);
  assert.equal(isSafeTotpEnrollmentSecret("JBSWY3DP-HPK3PXP"), false);
  assert.equal(isSafeTotpEnrollmentSecret("A".repeat(129)), false);
});

test("TOTP QR validation accepts real Supabase SVG response shapes", () => {
  const realisticSvg = createSupabaseQrSvg(8);

  assert.equal(isSafeTotpQrCode(asRawSvgDataUri(realisticSvg)), true);
  assert.equal(
    isSafeTotpQrCode(asPercentEncodedSvgDataUri(realisticSvg)),
    true,
  );
});

test("TOTP QR validation accepts large and near-bound Supabase SVGs", () => {
  const largeSvgDataUri = asRawSvgDataUri(createSupabaseQrSvg(1_900));
  const rectPairLength = blackQrRect.length + whiteQrRect.length;
  const nearBoundRectPairs = Math.floor(
    (990_000 - totpQrCodePrefix.length - supabaseSvgHeader.length - 7) /
      rectPairLength,
  );
  const nearBoundSvgDataUri = asRawSvgDataUri(
    createSupabaseQrSvg(nearBoundRectPairs),
  );

  assert.ok(largeSvgDataUri.length >= 275_000);
  assert.ok(largeSvgDataUri.length <= 285_000);
  assert.equal(isSafeTotpQrCode(largeSvgDataUri), true);
  assert.ok(nearBoundSvgDataUri.length >= 980_000);
  assert.ok(nearBoundSvgDataUri.length < 1_000_000);
  assert.equal(isSafeTotpQrCode(nearBoundSvgDataUri), true);
});

test("TOTP QR validation rejects empty and non-SVG payloads", () => {
  const rejectedPayloads = [
    totpQrCodePrefix,
    `${totpQrCodePrefix}%20%09%0A`,
    `${totpQrCodePrefix}not-svg`,
    `${totpQrCodePrefix}${encodeURIComponent("plain text")}`,
    `${totpQrCodePrefix}${encodeURIComponent("<html></html>")}`,
    `${totpQrCodePrefix}${encodeURIComponent('{"svg":true}')}`,
    `${totpQrCodePrefix}${encodeURIComponent('<?xml version="1.0"?>')}`,
  ];

  for (const value of rejectedPayloads) {
    assert.equal(isSafeTotpQrCode(value), false, value);
  }
});

test("TOTP QR validation rejects malformed or unsupported SVG documents", () => {
  const rejectedSvgDocuments = [
    '<svg width="10" height="10" xmlns="http://www.w3.org/2000/svg">',
    '<svg width="10" height="10" xmlns="http://www.w3.org/2000/svg"><rect></svg>',
    '<svg width="10" height="10" xmlns="http://www.w3.org/2000/svg"><path/></svg>',
    '<svg width="10" height="9" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="1" height="1" style="fill:black;stroke:none"/><rect x="1" y="0" width="1" height="1" style="fill:white;stroke:none"/></svg>',
    '<svg width="10" height="10" xmlns="http://www.w3.org/2000/svg"><script/></svg>',
    '<svg width="10" height="10" xmlns="http://www.w3.org/2000/svg"><foreignObject/></svg>',
  ];

  for (const svg of rejectedSvgDocuments) {
    assert.equal(isSafeTotpQrCode(asRawSvgDataUri(svg)), false, svg);
  }
});

test("TOTP QR validation rejects URLs, wrong data forms, and invalid encoding", () => {
  const rejectedValues = [
    "https://evil.example/qr.svg",
    "http://evil.example/qr.svg",
    "//evil.example/qr.svg",
    "javascript:alert(1)",
    "data:text/html,<svg></svg>",
    "data:image/png;base64,AAAA",
    "data:image/svg+xml;base64,PHN2Zz48L3N2Zz4=",
    `${totpQrCodePrefix}%E0%A4%A`,
    `${totpQrCodePrefix}%`,
  ];

  for (const value of rejectedValues) {
    assert.equal(isSafeTotpQrCode(value), false, value);
  }
});

test("TOTP QR validation rejects input above the pre-parse size bound", () => {
  assert.equal(
    isSafeTotpQrCode(
      asRawSvgDataUri(
        createSupabaseQrSvg(8).replace(
          "</svg>",
          `${" ".repeat(1_000_000)}</svg>`,
        ),
      ),
    ),
    false,
  );
});

test("TOTP factor inventories reject unsupported, duplicate, and malformed state", () => {
  const unverifiedFactor = {
    ...verifiedFactor,
    id: "34e770dd-9ff9-416c-87fa-43b31d7ef226",
    status: "unverified",
  };

  assert.deepEqual(getTotpFactorInventory([]), {
    unverified: [],
    verified: [],
  });
  assert.deepEqual(getTotpFactorInventory([unverifiedFactor]), {
    unverified: [unverifiedFactor],
    verified: [],
  });
  assert.deepEqual(getTotpFactorInventory([verifiedFactor]), {
    unverified: [],
    verified: [verifiedFactor],
  });
  assert.deepEqual(
    getTotpFactorInventory([
      unverifiedFactor,
      {
        ...unverifiedFactor,
        id: "34e770dd-9ff9-416c-87fa-43b31d7ef228",
      },
    ]),
    {
      unverified: [
        unverifiedFactor,
        {
          ...unverifiedFactor,
          id: "34e770dd-9ff9-416c-87fa-43b31d7ef228",
        },
      ],
      verified: [],
    },
  );
  assert.equal(
    getTotpFactorInventory([
      verifiedFactor,
      { ...verifiedFactor, factor_type: "phone" },
    ]),
    null,
  );
  assert.equal(
    getTotpFactorInventory([verifiedFactor, verifiedFactor]),
    null,
  );
  assert.equal(
    getTotpFactorInventory([
      { ...verifiedFactor, id: "not-a-factor" },
    ]),
    null,
  );
  assert.equal(
    getTotpFactorInventory([
      { ...verifiedFactor, status: "unexpected" },
    ]),
    null,
  );
});

test("AAL and verified factors produce fail-closed MFA states", () => {
  assert.equal(
    getMfaSessionState({
      currentLevel: "aal1",
      nextLevel: "aal1",
      verifiedTotpCount: 0,
    }),
    "enrollment-required",
  );
  assert.equal(
    getMfaSessionState({
      currentLevel: "aal1",
      nextLevel: "aal2",
      verifiedTotpCount: 1,
    }),
    "challenge-required",
  );
  assert.equal(
    getMfaSessionState({
      currentLevel: "aal2",
      nextLevel: "aal2",
      verifiedTotpCount: 1,
    }),
    "verified",
  );
  assert.equal(
    getMfaSessionState({
      currentLevel: "aal2",
      nextLevel: "aal1",
      verifiedTotpCount: 0,
    }),
    "stale-session",
  );
  assert.equal(
    getMfaSessionState({
      currentLevel: "aal2",
      nextLevel: "aal2",
      verifiedTotpCount: 0,
    }),
    "stale-session",
  );
  assert.equal(
    getMfaSessionState({
      currentLevel: "aal1",
      nextLevel: "aal2",
      verifiedTotpCount: 0,
    }),
    "stale-session",
  );
});

test("MFA challenge return paths remain within local Admin routes", () => {
  assert.equal(
    getSafeAdminRedirect("/admin/stories/123?mode=publish"),
    "/admin/stories/123?mode=publish",
  );
  assert.equal(getSafeAdminRedirect("https://evil.example/admin"), "/admin");
  assert.equal(getSafeAdminRedirect("//evil.example/admin"), "/admin");
  assert.equal(getSafeAdminRedirect("/stories/123"), "/admin");
});

test("MFA redirects reject protocol, encoding, control, and separator attacks", () => {
  const rejectedValues = [
    "https://evil.example",
    "//evil.example",
    "/\\evil.example",
    "/%2f%2fevil.example",
    "/%252f%252fevil.example",
    "javascript:alert(1)",
    "data:text/html,evil",
    "/admin%2f..%2f%2fevil.example",
    "/admin/%2e%2e/%2e%2e/evil",
    "/admin/%252e%252e/%252f%252fevil.example",
    "/admin/\u2215\u2215evil.example",
    "/admin/\uff0f\uff0fevil.example",
    "/admin/\uff3cevil.example",
    "/admin\nevil",
    " /admin",
    "/admin ",
    "/administrator",
  ];

  for (const value of rejectedValues) {
    assert.equal(getSafeAdminRedirect(value), "/admin", value);
  }

  assert.equal(
    getSafeAdminRedirect("/admin/stories?return=%2Fstories%2F123"),
    "/admin/stories?return=%2Fstories%2F123",
  );
});
