export type MfaAssuranceLevel = "aal1" | "aal2";

export type MfaFactorSummary = {
  factor_type: string;
  friendly_name?: string;
  id: string;
  status: string;
};

export type TotpFactorInventory = {
  unverified: MfaFactorSummary[];
  verified: MfaFactorSummary[];
};

export type MfaSessionState =
  | "challenge-required"
  | "enrollment-required"
  | "verified"
  | "stale-session";

const factorIdPattern =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const totpQrCodePrefix = "data:image/svg+xml;utf-8,";
const svgNamespace = "http://www.w3.org/2000/svg";
const svgXlinkNamespace = "http://www.w3.org/1999/xlink";
const svgXmlDeclaration = '<?xml version="1.0"?>';
const svgoGeneratedComment = "<!-- Generated by SVGo -->";
// Supabase Auth renders every QR module as an SVG rect, so valid enrollment
// payloads are commonly well above 100 KB. Keep a finite upper bound while
// allowing the SDK's trusted, in-memory data URI format.
const maxTotpQrCodeLength = 1_000_000;

function isXmlWhitespace(value: string) {
  return value === " " || value === "\t" || value === "\r" || value === "\n";
}

function readXmlAttributes(value: string) {
  const attributes = new Map<string, string>();
  let offset = 0;

  while (offset < value.length) {
    while (offset < value.length && isXmlWhitespace(value[offset])) {
      offset += 1;
    }

    if (offset === value.length) {
      break;
    }

    const nameMatch = /^[a-z_:][a-z0-9_.:-]*/i.exec(value.slice(offset));

    if (!nameMatch) {
      return null;
    }

    const name = nameMatch[0];
    offset += name.length;

    while (offset < value.length && isXmlWhitespace(value[offset])) {
      offset += 1;
    }

    if (value[offset] !== "=") {
      return null;
    }

    offset += 1;

    while (offset < value.length && isXmlWhitespace(value[offset])) {
      offset += 1;
    }

    const quote = value[offset];

    if (quote !== '"' && quote !== "'") {
      return null;
    }

    const closingQuote = value.indexOf(quote, offset + 1);

    if (closingQuote === -1 || attributes.has(name)) {
      return null;
    }

    const attributeValue = value.slice(offset + 1, closingQuote);

    if (
      attributeValue.includes("<") ||
      attributeValue.includes(">") ||
      attributeValue.includes("&")
    ) {
      return null;
    }

    attributes.set(name, attributeValue);
    offset = closingQuote + 1;

    if (offset < value.length && !isXmlWhitespace(value[offset])) {
      return null;
    }
  }

  return attributes;
}

function hasExactAttributes(
  attributes: Map<string, string>,
  requiredNames: string[],
) {
  return (
    attributes.size === requiredNames.length &&
    requiredNames.every((name) => attributes.has(name))
  );
}

function isSupabaseQrSvgDocument(value: string) {
  let svg = value.trim();

  if (!svg) {
    return false;
  }

  if (svg.startsWith(svgXmlDeclaration)) {
    svg = svg.slice(svgXmlDeclaration.length).trimStart();
  }

  if (svg.startsWith(svgoGeneratedComment)) {
    svg = svg.slice(svgoGeneratedComment.length).trimStart();
  }

  if (!svg.startsWith("<svg") || !isXmlWhitespace(svg[4])) {
    return false;
  }

  const openingTagEnd = svg.indexOf(">");

  if (openingTagEnd === -1) {
    return false;
  }

  const svgAttributes = readXmlAttributes(svg.slice(4, openingTagEnd));

  if (!svgAttributes) {
    return false;
  }

  const requiredSvgAttributes = svgAttributes.has("xmlns:xlink")
    ? ["width", "height", "xmlns", "xmlns:xlink"]
    : ["width", "height", "xmlns"];

  if (
    !hasExactAttributes(svgAttributes, requiredSvgAttributes) ||
    svgAttributes.get("xmlns") !== svgNamespace ||
    (svgAttributes.has("xmlns:xlink") &&
      svgAttributes.get("xmlns:xlink") !== svgXlinkNamespace)
  ) {
    return false;
  }

  const width = svgAttributes.get("width") ?? "";
  const height = svgAttributes.get("height") ?? "";

  if (!/^[1-9]\d{0,5}$/.test(width) || width !== height) {
    return false;
  }

  const closingTag = "</svg>";
  const documentBody = svg.slice(openingTagEnd + 1).trimEnd();

  if (!documentBody.endsWith(closingTag)) {
    return false;
  }

  const rects = documentBody.slice(0, -closingTag.length);
  let hasBlackModule = false;
  let hasWhiteModule = false;
  let offset = 0;

  while (offset < rects.length) {
    while (offset < rects.length && isXmlWhitespace(rects[offset])) {
      offset += 1;
    }

    if (offset === rects.length) {
      break;
    }

    if (!rects.startsWith("<rect", offset) || !isXmlWhitespace(rects[offset + 5])) {
      return false;
    }

    const rectEnd = rects.indexOf("/>", offset + 5);

    if (rectEnd === -1) {
      return false;
    }

    const rectAttributes = readXmlAttributes(
      rects.slice(offset + 5, rectEnd),
    );

    if (
      !rectAttributes ||
      !hasExactAttributes(rectAttributes, [
        "x",
        "y",
        "width",
        "height",
        "style",
      ]) ||
      !/^\d{1,6}$/.test(rectAttributes.get("x") ?? "") ||
      !/^\d{1,6}$/.test(rectAttributes.get("y") ?? "") ||
      !/^[1-9]\d{0,5}$/.test(rectAttributes.get("width") ?? "") ||
      rectAttributes.get("width") !== rectAttributes.get("height")
    ) {
      return false;
    }

    const style = rectAttributes.get("style");

    if (style === "fill:black;stroke:none") {
      hasBlackModule = true;
    } else if (style === "fill:white;stroke:none") {
      hasWhiteModule = true;
    } else {
      return false;
    }

    offset = rectEnd + 2;
  }

  return hasBlackModule && hasWhiteModule;
}

export function isTotpCode(value: string) {
  return /^\d{6}$/.test(value);
}

export function isPlausibleFactorId(value: string) {
  return factorIdPattern.test(value);
}

export function isSafeTotpEnrollmentSecret(value: string) {
  return value.length >= 16 && value.length <= 128 && /^[a-z2-7]+$/i.test(value);
}

export function isSafeTotpQrCode(value: string) {
  if (
    typeof value !== "string" ||
    value.length > maxTotpQrCodeLength ||
    !value.startsWith(totpQrCodePrefix)
  ) {
    return false;
  }

  const payload = value.slice(totpQrCodePrefix.length);

  if (!payload) {
    return false;
  }

  try {
    return isSupabaseQrSvgDocument(decodeURIComponent(payload));
  } catch {
    return false;
  }
}

export function getTotpFactorInventory(
  factors: MfaFactorSummary[],
): TotpFactorInventory | null {
  const factorIds = new Set<string>();
  const inventory: TotpFactorInventory = {
    unverified: [],
    verified: [],
  };

  for (const factor of factors) {
    if (
      factor.factor_type !== "totp" ||
      !isPlausibleFactorId(factor.id) ||
      factorIds.has(factor.id) ||
      (factor.status !== "unverified" && factor.status !== "verified")
    ) {
      return null;
    }

    factorIds.add(factor.id);
    inventory[factor.status].push(factor);
  }

  return inventory;
}

export function findOwnedTotpFactor(
  factors: MfaFactorSummary[],
  factorId: string,
  requiredStatus: "unverified" | "verified",
) {
  if (!isPlausibleFactorId(factorId)) {
    return null;
  }

  return (
    factors.find(
      (factor) =>
        factor.id === factorId &&
        factor.factor_type === "totp" &&
        factor.status === requiredStatus,
    ) ?? null
  );
}

export function getMfaSessionState({
  currentLevel,
  nextLevel,
  verifiedTotpCount,
}: {
  currentLevel: MfaAssuranceLevel;
  nextLevel: MfaAssuranceLevel;
  verifiedTotpCount: number;
}): MfaSessionState {
  if (
    currentLevel === "aal2" &&
    nextLevel === "aal2" &&
    verifiedTotpCount > 0
  ) {
    return "verified";
  }

  if (
    currentLevel === "aal1" &&
    nextLevel === "aal2" &&
    verifiedTotpCount > 0
  ) {
    return "challenge-required";
  }

  if (
    currentLevel === "aal1" &&
    nextLevel === "aal1" &&
    verifiedTotpCount === 0
  ) {
    return "enrollment-required";
  }

  return "stale-session";
}
